a = input('Digite algo: ')
print(type(a))
print('É somente espaço: ', a.isspace())
print('É Alfabético: ', a.isalpha())
print('É um número: ', a.isnumeric())
print('É alfanumérico: ', a.isalnum())
print('Está em maiúsculo: ', a.isupper())
print('Está em minúsculo: ', a.islower())
print('Está captalizado: ', a.istitle())
print('É decimal: ', a.isdecimal())
